<div class="resume-header">
    Daniel Sheppard<br/>
    512-906-7416<br/>
    <a href="mailto:danielsheppard@veryboring.net">danielsheppard@veryboring.net</a><br/>
    Resident of Austin, Texas
</div>

<div class="resume-cover">
    So why does my resume say "Big Daddy Death Ray's Music Project Remote Collaboratorizer" at the top?
    Well what better way to show off what I'm working on. A few months ago one of the sites I'm working with
    changed over to a new piece of software based in the Zend Framework. Since then I've become very interested
    in learning to program in ZF. I've dealt with a few other MVC frameworks in the past, but so far I think
    ZF takes the cake as the single most robust and at the same time straightforward MVC frameworks out there.
    So I've started building a pet project here, and I've stuck my resume in the middle of it. The full source code
    for this project is stored in my Github repository <a href="" target="_blank">here</a>.
</div>