<div class="resume-header">
    <center><h3><b>Resume</b></h3><br/>
    Daniel Sheppard<br/>
    512-906-7416<br/>
    <a href="mailto:danielsheppard@veryboring.net">danielsheppard@veryboring.net</a><br/>
    Resident of Austin, Texas
    </center>
</div>

<div class="resume-cover">
    So why does my resume say "Big Daddy Death Ray's Music Project Remote Collaboratorizer" at the top?
    Well what better way to show off what I'm working on. A few months ago one of the sites I'm working with
    changed over to a new piece of software based in the Zend Framework. Since then I've become very interested
    in ZF. I've dealt with a few other MVC frameworks in the past, but so far I think
    ZF takes the cake as the single most robust and at the same time straightforward MVC frameworks out there.
    So I've started building a pet project here, and I've stuck my resume in the middle of it. The full source code
    for this project is stored in my Github repository <a href="https://github.com/gutbunny/BigDDRMusiProRemCo" target="_blank">here</a>.
    <BR/>
    <br/>
    So by now you should have guessed that I'm a LAMP stack programmer, and that's what I'm hoping to continue to be
    in the forseeable future. Here's a quick outline of my skills.
    <ul>
        <li>Languages - PHP5 (heavy on the OOP-MVC), AJAX, Javascript/JQuery, CSS, ActionScript, XML, HTML, SOAP</li>

        <li>Database Technologies - MySQL, PostgreSQL, MSSQL </li>

        <li>Development Support Technologies - Subversion, Git, CVS, Beanstalk, Basecamp </li>

        <li>Applications - NetBeans, Flash, Photoshop, Fireworks, 3DS Max, iMovie, ProTools, MS Office, etc</li>

        <li>Operating Systems - RedHat, Ubuntu, Debian, CentOS, BSD, Windows NT/2Kx/7, Mac OS X, Mac < OS 9, DOS</li>

        <li>E-commerce - Authorize.net, Paypal, Bank of America gateways. OsCommerce, Ubercart, XCart and many more platforms.</li>
    </ul>
    <br>
    This is a short list just to give you the idea of where my skillset is. I could probably fill a page with just this list
    but let's move on.
</div>

<div class="resume-experience">
    <div class="resume-experience-header">
        Self Employed, Austin, TX
        <br/>January 1998 - Present
        <br/>Developer and Graphic Designer
    </div>
    <div class="resume-experience-body">
        For over a decade now I've been taking on projects of varying scope and complexity.
        I've always had at least one project going on, whether I've been working 9 to 5 in an
        office for someone else or not. However for the most part now I've settled in to a sort
        of limbo, somewhere between being a freelancer and an employee. I am still currently a contractor
        for one client, however the position requires me to behave more like an employee. I'm hoping to
        leave this limbo behind and settle in to a position that allows me to do more development of new software
        and less support of existing software. I find engineering and building much more rewarding.
        <br/>
        <br/>
        Current url's:<br/>
        <a href="http://mycollegescout.com" target="_blank">http://mycollegescout.com</a><br/>
        <a href="http://dev.mycollegescout.com" target="_blank">http://dev.mycollegescout.com</a>
        <br/><br/>
        Reference: Kelly Hill - CEO PPX Inc. My College Scout<br/>
        <a href="mailto:kellyhill@mycollegescout.com">kellyhill@mycollegescout.com</a>

    </div><br/>
    <div class="resume-experience-header">
        Insight Strategy & Logic Inc, San Francisco, CA
        <br/>October 2007 - April 2008
        <br/>Developer
    </div>
    <div class="resume-experience-body">
        Developed new websites in php/mysql in the Drupal 'framework'. Supported older systems in a variety of frameworks.
    </div><br/>
    <div class="resume-experience-header">
        Interactive Life Forms INC, Austin, TX
        <br/>October 2004 - July 2006
        <br/>Lead Developer / IT Director
    </div>
    <div class="resume-experience-body">
        My duties included programming in PHP/MySQL, database managment and design including design of ndb/cluster databases, Flash Actionscript programming in the early days of my employment, and SEO. I also spent more than a year working with the company's OsCommerce based shopping carts.
    </div><br/>
    <div class="resume-experience-header">
        Trim International, Pensacola, FL
        <br/>February 2004 - December 2004
        <br/>IT Director / Lead Programmer
    </div>
    <div class="resume-experience-body">
        I lead the development of web-based applications to handle order entry, MLM structure control, customer tracking, accounting, and many other complex aspects of the business cycle for one of the major sellers of health suppliments in North America. My duties also included coordinating team members, and the ever present need for support. After hurricane Ivan seriously dammaged my home in Pensacola, I chose not to return, but continued my duties remotely for another 3 months until my replacements could be found and trained.
    </div><br/>
    <div class="resume-experience-header">
        AMC Marketing, Kansas City, MO
        <br/>February 2000 - March 2002
        <br/>Web Developer
    </div>
    <div class="resume-experience-body">
        You know those late night television commercials advertising stuff for 19.95 through this special TV offer? Well just imagine websites of the same kind and you'll understand what I did at AMC Marketing.
    </div>
</div>