<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>index</title>
</head>
<body>
    <div id="table-data" style="min-height: 290px;">
        <table border="0" width="100%">
            <tr style="vertical-align:top;">
                <td>
                    <div class="table-data-header">
                        Profile Info
                    </div>
                    <br/>
                    <div id="personal-info-names">
                        <?php echo $this->user['gb_users_firstname'] . " " . $this->user['gb_users_lastname']; ?>
                    </div>
                    <div id="personal-info-email">
                        <?php echo $this->user['gb_users_email']; ?>
                    </div>
                </td>
                <td>
                    <div class="table-data-header">
                        My Projects
                    </div>
                    <br/>
                    <?php // LOOP OVER PROJECTS ?>


                    <?php // END PROJECTS LOOP ?>
                </td>
            </tr>
        </table>
    </div>
  <a href="user/edituser">Edit My Account</a>
  <?php print_r($this->sanity); ?>
</body>
</html>
